apiVersion: apps/v1
kind: Deployment
metadata:
  name: geocoding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: geocoding
  template:
    metadata:
      labels:
        app: geocoding
    spec:
      containers:
      - name: geocoding
        image: ghcr.io/silkenbread/fastapi-leaflet:lastest
        ports:
        - containerPort: 8095

---

apiVersion: v1
kind: Service
metadata:
  name: geocoding
spec:
  type: NodePort  # Agregar esta línea
  selector:
    app: geocoding
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 8095
